Add pypi deployment via Travis
src-d/minhashcuda pull request #3
Opened 2018-02-27 11:40 UTC by zurk

Signed-off-by: Konstantin Slavnov konstantin@sourced.tech

2018-02-27 13:11 UTC, vmarkovtsev requested changes

2018-02-27 13:11 UTC, vmarkovtsev commented on .travis.yml
> +      after_script: skip
Do you need `after_script: skip` here?

2018-02-27 13:11 UTC, vmarkovtsev commented on .travis.yml
> +  - . .travis.setup
Better `.travis.install`

2018-02-27 13:11 UTC, vmarkovtsev commented on .travis.yml
> +install:
Move it to the "build" stage. I know that not necessary but still will be more explicit

2018-02-27 14:25 UTC, zurk commented
Also I find one more problem:
```
[0K$ twine upload dist/*manylinux* -u $PYPI_LOGIN -p $PYPI_PASS

  0%|          | 0.00/44.2M [00:00<?, ?bytes/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 44.1M/44.2M [00:00<00:00, 612kbytes/s]
                                                       
Uploading distributions to https://upload.pypi.org/legacy/
Uploading libMHCUDA-2.0.2-cp34-cp34m-manylinux1_x86_64.whl
HTTPError: 403 Client Error: The user '[secure]' is not allowed to upload to project 'libMHCUDA'. See https://pypi.org/help#project-name for more information. for url: https://upload.pypi.org/legacy/

travis_time:end:1bf1826c:start=1519741115503683766,finish=1519741119985534458,duration=4481850692
[0Ktravis_fold:end:after_script
[0K
Done. Your build exited with 0.
```

in case of error, twine returns the error message instead of 1 code (https://github.com/pypa/twine/blob/master/twine/__main__.py#L27).
I can make a PR to twine, but any ideas how to work around it for now?

2018-02-27 14:29 UTC, zurk commented on .travis.yml
> +install:
if I move it here deploy fails:
```
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0', '.')' returned non-zero exit status 1
...
auditwheel: command not found
...
twine: command not found
...
```
and it looks like `install` does not run for this stage. 

See full logs: https://api.travis-ci.org/v3/job/346796133/log.txt

2018-02-27 14:36 UTC, zurk commented
And this is not outdated. https://github.com/src-d/minhashcuda/pull/3/commits/581f860b6ecb66bd07700cdfd69c88df983b9be2#r170938977

2018-02-27 14:57 UTC, vmarkovtsev commented on .travis.yml
> +install:
You need to debug this because it works perfectly and I did it multiple times, e.g. https://github.com/vmarkovtsev/ggmbox/blob/master/.travis.yml

2018-02-27 15:23 UTC, zurk commented on .travis.yml
> +install:
but you do not use stages in your example...

2018-02-27 15:38 UTC, zurk commented
ok, I can do like that. ^

2018-02-27 15:52 UTC, vmarkovtsev requested changes

2018-02-27 15:52 UTC, vmarkovtsev commented on .travis.yml
> +    - stage: build
I don't see much changes...

Also `script` should run the tests, not install.

And be aware that this project is actually C++. There are python bindings, but there can be other bindings too. Don't nail it to Python.

2018-02-27 15:59 UTC, vmarkovtsev commented
@zurk 

```yaml
dist: trusty
sudo: required

matrix:
  include:
    - language: python
      python:
        - "3.4"
        - "3.5"
        - "3.6"
      env:
        - CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0
      install: . .python.install
      deploy:
        - if tag
        - twine upload dist/*manylinux* -u $PYPI_LOGIN -p $PYPI_PASS
      language: cpp
      install:
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..
notifications:
  email: false
```

2018-02-28 11:38 UTC, zurk commented
@vmarkovtsev I adopt your script.
for any reason 
```
python:
  - 3.4
  - 3.5
  - 3.6
```
does not work at all. and any modifications of this code. 
Also, deployment stage fails with  gives zero-information message:
```
[33mInstalling deploy dependencies[0m

!!! Script support is experimental !!!


travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
Script failed with status 127

travis_fold:end:dpl.3
failed to deploy
```

But It should be the same as I share earlier https://github.com/src-d/minhashcuda/pull/3#issuecomment-368894722. You should to add PyPI login and password to Travis settings to `$PYPI_LOGIN` and `$PYPI_PASS` env vars.

2018-02-28 12:08 UTC, vmarkovtsev commented
@zurk If setting several python versions do not work - grow the matrix and use YAML pointers to be DRY.

2018-02-28 12:09 UTC, vmarkovtsev commented
I will add the login and password as soon as we merge this.

2018-02-28 12:29 UTC, zurk commented
>  grow the matrix and use YAML pointers to be DRY.
I think I did exactly what you are saying

2018-03-01 10:17 UTC, vmarkovtsev requested changes

2018-03-01 10:17 UTC, vmarkovtsev commented on .travis.yml
> +      before_install:
You don't need virtualenv in this ephemeral environment, nothing to isolate from. Each job runs in a separate instance.

2018-03-01 10:17 UTC, vmarkovtsev commented
@zurk Almost there

2018-03-01 10:59 UTC, zurk commented
Yes, now it works without virtualenv activation. Before I have some troubles. Looks like artifact while searching how to make it work.

2018-03-01 11:34 UTC, vmarkovtsev approved these changes

2018-03-01 11:35 UTC, merged